config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :items do
    member do
      post :add_to_cart
    end
      
    resources :comments, only:[:create]
  end
  
  #cart
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  #orders
  resources :orders, only:[:index, :show, :create] do
    member do
    delete :cancel
    end 
  end 

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  root "items#index"
  
  # APIs
  namespace :api do         
    namespace :v1 do        
      resources :items, only:[] do   
        member do             
          post :favorite          
        end                 
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# cart.rb

class Cart

  attr_reader :items


  def initialize(items = [])
    @items = items
  end

  def add_item(item_id)
    #check if item_id is same
    found_item = items.find { |item| item.item_id == item_id}

    if found_item
      #found will return the found item_id, .class will show CartItem
      found_item.increment!
    else
      items << CartItem.new(item_id)
    end

  end

  def empty?
    items.empty?
  end


  def total 
    result = items.sum { |item| item.total }
    # @items.reduce(0) { |sum, item| sum + item.total}
    # tmp = 0
    # @items.each do |item|
    #   tmp += item.total
    # end
    # tmp

    #april fool 90% off
    if Time.now.month == 4 and Time.now.day == 1
      result = result * 0.1
    end

    result
  end

  def self.from_hash(hash = nil)    #class method
    if hash && hash["items"] 
      # items = []

      # hash["items"].each do |item|
      #   items << CartItem.new(item["item_id"], item["quantity"])
      # end

      items = hash["items"].map { |item| 
        CartItem.new(item["item_id"], item["quantity"])
      }

      # Cart.new(items)
      new items
    else
      # Cart.new
      new
    end
  end

  def to_hash

    # items = []
    # @items.each do |item|
    #   items << { "item_id" => item.item_id, 
    #              "quantity" => item.quantity } 
    # end

    items = @items.map { |item| 
      { "item_id" => item.item_id, "quantity" => item.quantity } 
    }

    result = {
        "items" => items
      }
  end
end

app/models/cart_item.rb
# cart_item.rb

class CartItem
  attr_reader :item_id, :quantity

  def initialize(item_id, quantity = 1)
    @item_id = item_id
    @quantity = quantity
  end

  def increment!(n = 1)
    @quantity += n
  end

  def item
    #return the specific cart_item
    Item.find(item_id)
  end

  def total
    item.price * quantity
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: {minimum: 2}

  belongs_to :user
  belongs_to :item

  default_scope { order(id: :desc).where(deleted_at: nil) }
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :histories
  has_many :users, through: :histories
end

app/models/favorite_item.rb
class FavoriteItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, 
                    numericality: { greater_than: 0 }
  #relationships
  belongs_to :category 
  has_many :comments
  has_many :favorite_items
  has_many :users, through: :favorite_items
  
  has_one_attached :cover
  

  # scope :available, -> {where(deleted_at: nil)}
  default_scope {where deleted_at: nil}                


  def destroy
    @item.update(deleted_at: Time.now)
  end

  def favorited_by(u)
    u.items.include?(self)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  attr_reader :nonce
  belongs_to :user
  has_many :order_items

  before_create :create_order_num



  aasm column: 'status' do # default column: aasm_state
    state :unprocessed, initial: true
    state :paid, :delivered, :cancelled

    event :pay do
      transitions from: :unprocessed, to: :paid
      after_transaction do
        puts "-----------------"
        puts "send SNS"
        puts "-----------------"
      end
    end

    event :deliver do
      transitions from: :paid, to: :delivered
    end
    event :cancel do
      transitions from: [:unprocessed, :paid], to: :cancelled
    end
  end

  private

  def create_order_num
    self.order_num = num_generator
  end

  def num_generator
    year = Date.today.year
    month = Date.today.month
    day = Date.today.day
    code = [*0..9, *'A'..'Z'].sample(6).join
    today = "#{year}#{"%02d" % month}#{"%02d" % day}#{code}"

    return today
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, 
                       confirmation: true, 
                       length: { minimum: 4 }

  #relationships
  has_many :histories
  has_many :events, through: :histories
  has_many :comments

  has_many :favorite_items
  has_many :items, through: :favorite_items

  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show

  end

  def destroy
    session[:carty] = nil
    redirect_to root_path, notice: 'The cart is empty!'
  end

  def checkout
    @order = Order.new
    @token = gateway.client_token.generate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinbendon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head_js%>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>
    <div class="container mt-3 mb-3">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<!-- _flash.html.erb -->
<% if flash[:notice] %>
	<div class="alert alert-success" role="alert" data-controller="flash" data-target="flash.message">
		<%= flash[:notice] %>
		<button class="close" data-action="flash#close">
			<i class="fa fa-times"></i>
		</button>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger" role="alert">
	  <%= flash[:alert] %>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<p>2020 &copy; dinbendon</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">呷飽未</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <!-- home/link/dropdown -->
      <ul class="navbar-nav mr-auto order-1">
        <li class="nav-item">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Order", items_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Start A Event","#", class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Order", items_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a href="/sign_up" class="nav-link">Sign up</a>
          </li>
          <li class="nav-item">
            <a href="/login" class="nav-link">Login</a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto order-2">
        <% if current_user %>
          <li class= "nav-item">
            <%= link_to cart_path, class: "nav-link" do %>
              Cart <i class='fas fa-shopping-cart'></i>
              <%= current_cart.items.count %>
            <% end %>
          </li>
          <li class="nav-item nav-link">Hi, <%= current_user.email%></li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: 'delete', class: "nav-link" %> 
          </li>
        <% end %>
      </ul>
        
      
  </div>
</nav>