config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :items do
    member do
      post :add_to_cart
    end
      
    resources :comments, only:[:create]
  end
  
  #cart
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  #orders
  resources :orders, only:[:index, :show, :create] do
    member do
    delete :cancel
    end 
  end 

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  root "items#index"
  
  # APIs
  namespace :api do         
    namespace :v1 do        
      resources :items, only:[] do   
        member do             
          post :favorite          
        end                 
      end
    end
  end
end

app/models/cart.rb
# cart.rb

class Cart

  attr_reader :items


  def initialize(items = [])
    @items = items
  end

  def add_item(item_id)
    #check if item_id is same
    found_item = items.find { |item| item.item_id == item_id}

    if found_item
      #found will return the found item_id, .class will show CartItem
      found_item.increment!
    else
      items << CartItem.new(item_id)
    end

  end

  def empty?
    items.empty?
  end


  def total 
    result = items.sum { |item| item.total }
    # @items.reduce(0) { |sum, item| sum + item.total}
    # tmp = 0
    # @items.each do |item|
    #   tmp += item.total
    # end
    # tmp

    #april fool 90% off
    if Time.now.month == 4 and Time.now.day == 1
      result = result * 0.1
    end

    result
  end

  def self.from_hash(hash = nil)    #class method
    if hash && hash["items"] 
      # items = []

      # hash["items"].each do |item|
      #   items << CartItem.new(item["item_id"], item["quantity"])
      # end

      items = hash["items"].map { |item| 
        CartItem.new(item["item_id"], item["quantity"])
      }

      # Cart.new(items)
      new items
    else
      # Cart.new
      new
    end
  end

  def to_hash

    # items = []
    # @items.each do |item|
    #   items << { "item_id" => item.item_id, 
    #              "quantity" => item.quantity } 
    # end

    items = @items.map { |item| 
      { "item_id" => item.item_id, "quantity" => item.quantity } 
    }

    result = {
        "items" => items
      }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show

  end

  def destroy
    session[:carty] = nil
    redirect_to root_path, notice: 'The cart is empty!'
  end

  def checkout
    @order = Order.new
    @token = gateway.client_token.generate
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<!-- _cart.html.erb -->

<% if !current_cart.empty?%>
	<div>
		<table class="table">
			<thead>
				<tr>
					<th>Food</th>
					<th>Amount</th>
					<th>Price</th>
				</tr>
			</thead>
			<tbody>
				<% current_cart.items.each do |cart_item|%>
				<tr>
					<td><%= cart_item.item.name %> ( $<%= cart_item.item.price %> )</td>
					<td><%= cart_item.quantity %></td>
					<td><%= cart_item.total %></td>
				</tr>
				<% end %>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">Total</td>
					<td><%= current_cart.total %></td>
				</tr>
			</tfoot>
		</table>
	</div>
<% end %>

app/views/carts/checkout.html.erb
<!-- checkout.html.erb -->
<%= content_for :head_js do %>
	<script src="https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.min.js"></script>
<%end %>	
	



<h1>Checkout</h1>

<%= render 'cart' %>

<%= form_for(@order) do |form|%>
	<div>
		<%=form.label :receiver%>
		<%=form.text_field :receiver%>
	</div>

	<div>
		<%=form.label :phone%>
		<%=form.text_field :phone%>
	</div>

	<div>
		<%=form.label :address%>
		<%=form.text_field :address%>
	</div>
	
	<%=form.hidden_field :nonce%>

	<div id = "dropin-container">
		
	</div>	
	<%= form.submit "Submit", id: 'submit-order'%>

<%end%>

<script>
	button = document.querySelector("#submit-order");
	let nonce_field = document.querySelector("#order_nonce");
	let form = document.querySelector("#new_order");

	braintree.dropin.create({
      authorization: '<%= @token %>',
      container: '#dropin-container'
    }, function (createErr, instance) {
      button.addEventListener('click', function (e) {
      	e.preventDefault();
        instance.requestPaymentMethod(function (err, payload) {
          nonce_field.value = payload.nonce;
          // alert(payload.nonce);
          form.submit();
          // Submit payload.nonce to your server
        });
      });
    });
	
</script>

app/views/carts/show.html.erb
<!-- show.html.erb -->

<div class="mb-3">
	<h1 >
		Cart 
		<%= link_to "Clear Cart", cart_path, method: 'delete', class:'btn btn-sm btn-success' unless current_cart.empty? %>
	</h1>

</div>
<%= render 'cart' %>
<div>
	<%= link_to"Buy More", root_path, class:'btn btn-primary'%>


	<%= link_to"Pay", checkout_cart_path, class:'btn btn-danger' unless current_cart.empty? %>

</div>