config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :items do
    member do
      post :add_to_cart
    end
      
    resources :comments, only:[:create]
  end
  
  #cart
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  #orders
  resources :orders, only:[:index, :show, :create] do
    member do
    delete :cancel
    end 
  end 

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  root "items#index"
  
  # APIs
  namespace :api do         
    namespace :v1 do        
      resources :items, only:[] do   
        member do             
          post :favorite          
        end                 
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, 
                    numericality: { greater_than: 0 }
  #relationships
  belongs_to :category 
  has_many :comments
  has_many :favorite_items
  has_many :users, through: :favorite_items
  
  has_one_attached :cover
  

  # scope :available, -> {where(deleted_at: nil)}
  default_scope {where deleted_at: nil}                


  def destroy
    @item.update(deleted_at: Time.now)
  end

  def favorited_by(u)
    u.items.include?(self)
  end

end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  # skip_before_action :check_login # so that guest can see

  def favorite
    item = Item.find(params[:id])

    
    if item.favorited_by(current_user)
      current_user.items.delete(item)
      render json: {status: 'removed'}
    else
      current_user.items << item
      render json: {status: 'favorited'}
    end

    # render json: {name: 'aaa', age: 18}
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy, :add_to_cart]
                            # excepte:[ :index, :new, :create]

  def index
    @items = Item.all
  end

  def show
    # @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.includes(:user) #eager loading

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: 'Add new order!'
    else
      render :new
    end
  end

  def edit
    # find_item
    # @item = Item.find(params[:id])
  end

  def update
    #no need a page, just complete the action
    # find_item
    # @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path, notice: 'Your order is updated!'
    else
      render :edit
    end
  end

  def destroy
    # find_item
    # @item.destroy
    @item.update(deleted_at: Time.now)

    redirect_to items_path, notice: 'Delete the order'
  end

  def add_to_cart
    # cart = Cart.from_hash(session[:carty])
    current_cart.add_item(@item.id)
    session[:carty] = current_cart.to_hash

    redirect_to root_path, notice: 'The item is added!'
  end

  private
  def find_item
    @item = Item.find(params[:id])
    # @item = Item.find_by!(params[:id], deleted_at: nil)
  end
  def item_params
    #only permit these variable, no user can send other variable via browser
    params.require(:item).permit(:name, 
                                 :description, 
                                 :price, 
                                 :spec,
                                 :cover,
                                 :category_id)
  end

  
end

app/helpers/api/v1/items_helper.rb
module Api::V1::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<!-- _form.html.erb -->

<%= form_for(item) do |f| %>

  <% if item.errors.any? %>
    <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>
  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.label :spec %>
    <%= f.text_field :spec %>
  </div>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<!-- edit.html.erb -->

<h1>Edit Orders</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<h1>Your Orders</h1>

<%= link_to "Add new", new_item_path %>

	<div class="row">
		
		<% @items.each do |item| %>
			<div class="col-4 mb-3 item">
				<div class="card" >
				   		<%= image_tag item.cover.variant(resize_to_limit: [100, 100]), class: "cover-image" if item.cover.attached? %>
				  	<div class="card-body">
					  	<h5 >
					  		<%= link_to item.name, item_path(item.id), class: "card-title" %>
					  			
					  	</h5>
					  	<p class="card-text">
							<%= link_to "Edit", edit_item_path(item.id) , class: "btn btn-primary"%>

							<%= link_to "Delete", item_path(item.id), method: 'delete', data: {confirm: "Do you really want to delete?"}, class: "btn btn-success" %>
							<%= link_to "Add to Cart", add_to_cart_item_path(item),method: "POST" , class: "btn btn-danger"%>   	
						</p>
				    </div>
				</div>  
			</div>
		<% end %>


	</div>

app/views/items/new.html.erb
<h1>Add New Order</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<h1 data-controller="item">
	<%= @item.name %>
	($: <%= @item.price %>)
	<a href="#" class="btn btn-outline-danger" data-action="item#heart">
		
		<% if @item.favorited_by(current_user)%>
			<i class="fas fa-heart" data-target="item.icon"></i>
		<% else%>
			<i class="far fa-heart" data-target="item.icon"></i>
		<% end %>

	</a>
	<%= link_to "Add to Cart", add_to_cart_item_path(@item),method: "POST" , class: "btn btn-outline-danger"%>  

</h1>



<div data-controller="comment">
	<h3>Comment</h3>
	<%= form_for(@comment, url:item_comments_path(@item), remote: true) do |form|%>
			<input type="hidden" id="item_id" value="<%= @item.id %>">

			<div class="form-group mb-3">
				<%= form.text_area :content,
							  class: 'form-control',
							  data: {target: 'comment.content',
							  action: 'keyup->comment#check'} %>
			</div>
			<%= form.submit class: 'btn btn-success mb-3',
							disabled: true,
							data: {target:'comment.submit'} %>
	
	<%end %>
</div>


<div id="comments">
	<% @comments.each do |comment| %>
		<%= render 'comments/comment', comment: comment %>
	<% end %>
		
</div>